sudo: required
# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- sudo apt-get libblas-dev liblapack-dev
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2

script:
  - stack --no-terminal --skip-ghc-check --install-ghc test

after_script:
#  - stack install codecov-haskell
#  - codecov-haskell testQubitZero